<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>HallownestWayfinder</AssemblyName>
    <RootNamespace>HallownestWayfinder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HKBuildUtils" Version="0.6.1" PrivateAssets="all" />
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Include="Assets\*.png" />
    <EmbeddedResource Include="Assets\vanilla_transitions.txt" />
    <EmbeddedResource Include="Assets\localization_en.txt" />
    <EmbeddedResource Include="Assets\localization_pt.txt" />
  </ItemGroup>
</Project>
